CRUD_MVC/Controllers/EmployeeController.cs
using CRUD_MVC.Models;
using CRUD_MVC.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD_MVC.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeRepository _employeeRepository;

        public EmployeeController(IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }

        public IActionResult Index()
        {
            List<EmployeeModel> model = _employeeRepository.GetAll();

            return View(model);
        }

        public IActionResult AddNewEmployee()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddNewEmployee(EmployeeModel employee)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _employeeRepository.Add(employee);
                    TempData["Success"] = $"Employee {employee.FirstName} {employee.LastName} successfully added.";
                    return RedirectToAction("Index");
                }

                return View(employee);
            }
            catch(System.Exception e)
            {
                TempData["Error"] = $"Ops, something went wrong: {e.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult EditEmployeeView(int id)
        {
            EmployeeModel employee = _employeeRepository.GetEmployee(id);

            return View(employee);
        }

        public IActionResult EditEmployee(EmployeeModel employee)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _employeeRepository.Update(employee);
                    TempData["Success"] = $"Employee {employee.FirstName} {employee.LastName} successfully edited.";
                    return RedirectToAction("Index");
                }

                return View("EditEmployeeView", employee);
            }
            catch(System.Exception e)
            {
                TempData["Error"] = $"Ops, something went wrong: {e.Message}";
                return View("EditEmployeeView", employee);
            }
        }

        public IActionResult DeleteEmployee(int id)
        {
            try
            {
                EmployeeModel deletedEmployee = _employeeRepository.DeleteEmployee(id);
                TempData["Success"] = $"Employee {deletedEmployee.FirstName} {deletedEmployee.LastName} successfully deleted.";
                return RedirectToAction("Index");
            }
            catch(System.Exception e)
            {
                TempData["Error"] = $"Ops, something went wrong: {e.Message}";
                return RedirectToAction("Index");
            }
        }

        
    }
}

CRUD_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Simple CRUD Page</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    
    @* Data Table *@
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.12.1/datatables.min.css" />
    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Simple CRUD Page</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Simple Crud Page
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.12.1/datatables.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>